import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SchemaProvider } from "./components/SchemaContext";
// import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Form Playground",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <SchemaProvider>
        <body className={inter.className}>{children}</body>
      </SchemaProvider>
    </html>
  );
}
